name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Deploy container
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no root@angelin.dev << 'EOF'
            cd repositories/alldrive
            git pull
            rm .env
            echo "API_PORT=${{ secrets.API_PORT }}" >> .env
            echo "API_HOST=${{ secrets.API_HOST }}" >> .env
            echo "FRONTEND_PORT=${{ secrets.FRONTEND_PORT }}" >> .env
            echo "FRONTEND_HOST=${{ secrets.FRONTEND_HOST }}" >> .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
            echo "DB_TYPE=${{ secrets.DB_TYPE }}" >> .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            docker-compose down
            docker-compose up -d
          EOF
