name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - run: npm i

      - name: Build frontend image
        run: |
          echo "API_HOST=${{ secrets.API_HOST }}" >> .env
          echo "FRONTEND_PORT=${{ secrets.FRONTEND_PORT }}" >> .env
          docker build -t alldrive_frontend -f apps/frontend/Dockerfile .

      - name: Build API image
        run: |
          echo "API_PORT=${{ secrets.API_PORT }}" >> .env
          echo "FRONTEND_HOST=${{ secrets.FRONTEND_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_TYPE=${{ secrets.DB_TYPE }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          docker build -t alldrive_api -f apps/api/Dockerfile .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push frontend image
        run: |
          docker tag alldrive_frontend:latest zeilar/alldrive_frontend:latest
          docker push zeilar/alldrive_frontend:latest

      - name: Push API image
        run: |
          docker tag alldrive_api:latest zeilar/alldrive_api:latest
          docker push zeilar/alldrive_api:latest

      - name: Deploy containers
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no root@angelin.dev << 'EOF'
            cd repositories/alldrive
            rm .env
            echo "API_PORT=${{ secrets.API_PORT }}" >> .env
            echo "API_HOST=${{ secrets.API_HOST }}" >> .env
            echo "FRONTEND_PORT=${{ secrets.FRONTEND_PORT }}" >> .env
            echo "FRONTEND_HOST=${{ secrets.FRONTEND_HOST }}" >> .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
            echo "DB_TYPE=${{ secrets.DB_TYPE }}" >> .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
            docker pull zeilar/alldrive_frontend:latest
            docker pull zeilar/alldrive_api:latest
            docker-compose down
            docker-compose up -d
          EOF
